lnt = input('enter-the-lenght-of-the-floor-in-square-feet.:')
wth = input('enter-the-with-of-the-floor-in-square-feet.:')
price = input("enter-the-price-of-a-square-foot-of-tiling-without-the-dollar-sign:")
a = str(lnt * wth * price)
print("the floor costs " + a + " dollars")
